---
- name: Actualizacion de paquetes de Ubuntu
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
    name: "*"
    state: latest
  become: true
  become_user: root
  become_method: sudo

- name: Instalacion de dependencias del Sistema Operativo
  ansible.builtin.apt:
    name: "{{ item }}"
    autoclean: true
    state: present
  with_items:
    - "{{ base_packages }}"
  become: true
  become_user: root
  become_method: sudo

- name: Instalacion de dependencias de pip
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ pip_packages }}"
  become: true
  become_user: root
  become_method: sudo
