---

- name: Creacion del archivo de htpasswd para autenticacion basica
  ansible.builtin.htpasswd:
    path: "{{ nginx_dir }}/{{ nginx_passwd_file_name }}"
    name: "{{ nginx_basic_user }}"
    password: "{{ nginx_user_password }}"
    mode : 0644

- name: Copiar index.html
  ansible.builtin.copy:
    src: "index.html"
    dest: "{{ html_dir }}"
  
- name: Template nginx.conf 
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_dir }}/nginx.conf"

