---

- name: Creacion de la base de datos de nginx con usuario
  ansible.builtin.htpasswd:
    path: "{{ base_config_dir }}/{{ nginx_dir }}/{{ nginx_passwd_file_name }}"
    name: "{{ nginx_basic_user }}"
    password: "{{ nginx_user_password }}"
    mode : 0644

- name: Copiar index.html
  ansible.builtin.copy:
    src: "index.html"
    dest: "{{ base_config_dir }}/{{ html_dir }}"
  
- name: Template nginx.conf 
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "{{ base_config_dir }}/{{ nginx_dir }}/nginx.conf"

