---
- name: Clave privada de OpenSSL
  community.crypto.openssl_privatekey:
    path: "{{ base_config_dir }}/{{ cert_dir }}/{{ ssl_key_file }}"
    size: 2048

- name: Generacion del signing request de OpenSSL
  community.crypto.openssl_csr:
    path: "{{ base_config_dir }}/{{ cert_dir }}/{{ ssl_csr_file }}"
    privatekey_path: "{{ base_config_dir }}/{{ cert_dir }}/{{ ssl_key_file }}"
    country_name: "{{ ssl_country_name }}"
    organization_name: "{{ ssl_org_name }}"
    email_address: "{{ ssl_email_address }}"
    common_name: "{{ ssl_common_name }}"
    organizational_unit_name: "{{ ssl_org_unit }}"

- name: Generar certificado autofirmado
  community.crypto.x509_certificate:
    path: "{{ base_config_dir }}/{{ cert_dir }}/{{ ssl_cert_file }}"
    privatekey_path: "{{ base_config_dir }}/{{ cert_dir }}/{{ ssl_key_file }}"
    csr_path: "{{ base_config_dir }}/{{ cert_dir }}/{{ ssl_csr_file }}"
    provider: selfsigned
