---
- name: Setup podman VM
  block:
    - name: Creacion de directorios de configuracion del contenedor
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ preconf_dirs }}"

    - ansible.builtin.include_tasks: "01-OSPackages.yml"
    - ansible.builtin.include_tasks: "02-nginx.yml"
    - ansible.builtin.include_tasks: "03-ssl.yml"
    - ansible.builtin.include_tasks: "04-podman.yml"
    - ansible.builtin.include_tasks: "05-k8s.yml"
    - ansible.builtin.include_tasks: "06-limpieza.yml"

  when:
    - "'vm' in group_names"
